// ═══════════════════════════════════════════════
//  RACKYWEB PROMOTE — MOCK DATA
// ═══════════════════════════════════════════════

export const STATS = [
  { label: 'Active Advertisers', value: 12480, suffix: '+', icon: '📢' },
  { label: 'Campaign Reach',     value: 4200000, suffix: '+', icon: '🌍' },
  { label: 'Businesses Promoted',value: 8750, suffix: '+', icon: '🏢' },
  { label: 'Monthly Visitors',   value: 950000, suffix: '+', icon: '👁️' },
];

export const CATEGORIES = [
  'All', 'Tech', 'Fashion', 'Education', 'Restaurants',
  'Media', 'AI', 'Finance', 'Real Estate', 'Events',
  'Jobs', 'Startups', 'Courses', 'Healthcare',
];

export const ADS = [
  {
    id: 1, featured: true,
    logo: '🚀', category: 'Tech',
    name: 'LaunchPad Africa',
    tagline: 'The #1 startup accelerator in West Africa',
    description: 'We help early-stage African startups raise funding, build products, and scale globally. Join 200+ alumni who have raised $150M+.',
    price: '₦50,000/mo', country: 'Nigeria',
    views: 24800, clicks: 3120,
    contact: '+2348012345678', whatsapp: '2348012345678',
    website: 'https://launchpadafrica.com',
    tags: ['Startup', 'Funding', 'Tech'],
    verified: true, trending: true,
    color: '#00f0ff',
  },
  {
    id: 2, featured: true,
    logo: '👗', category: 'Fashion',
    name: 'Zara Lagos',
    tagline: 'Premium Nigerian Fashion for the Modern Woman',
    description: 'Handcrafted Ankara and contemporary fusion wear. Custom designs, ready-to-wear collections, and wedding attire. Ships worldwide.',
    price: '₦25,000/mo', country: 'Nigeria',
    views: 18900, clicks: 2450,
    contact: '+2348098765432', whatsapp: '2348098765432',
    website: 'https://zarlagos.com',
    tags: ['Fashion', 'Ankara', 'Luxury'],
    verified: true, trending: false,
    color: '#ff0080',
  },
  {
    id: 3, featured: false,
    logo: '📚', category: 'Education',
    name: 'CodeCamp Nigeria',
    tagline: 'Learn to code in 12 weeks. Get hired.',
    description: 'Full-stack web development, data science, and UI/UX bootcamps. 94% job placement rate. Pay after you get hired.',
    price: '₦15,000/mo', country: 'Nigeria',
    views: 31200, clicks: 5600,
    contact: '+2347011223344', whatsapp: '2347011223344',
    website: 'https://codecampng.com',
    tags: ['Coding', 'Bootcamp', 'Career'],
    verified: false, trending: true,
    color: '#8b5cf6',
  },
  {
    id: 4, featured: true,
    logo: '🍽️', category: 'Restaurants',
    name: 'Jevinik Restaurant',
    tagline: 'Authentic Nigerian Cuisine Since 1991',
    description: 'Experience the best of Nigerian culinary heritage. From jollof rice to egusi soup, each dish tells a story of culture and flavor.',
    price: '₦20,000/mo', country: 'Nigeria',
    views: 15600, clicks: 1890,
    contact: '+2348055667788', whatsapp: '2348055667788',
    website: 'https://jevinikrestaurant.com',
    tags: ['Food', 'Nigerian', 'Dining'],
    verified: true, trending: false,
    color: '#ff6b35',
  },
  {
    id: 5, featured: false,
    logo: '📺', category: 'Media',
    name: 'Pulse Nigeria',
    tagline: 'Breaking News, Entertainment & Lifestyle',
    description: "Nigeria's fastest growing digital media brand. Reach 8 million monthly readers with targeted content advertising campaigns.",
    price: '₦35,000/mo', country: 'Nigeria',
    views: 52000, clicks: 8900,
    contact: '+2349012345678', whatsapp: '2349012345678',
    website: 'https://pulse.ng',
    tags: ['Media', 'News', 'Digital'],
    verified: true, trending: true,
    color: '#00f0ff',
  },
  {
    id: 6, featured: true,
    logo: '🤖', category: 'AI',
    name: 'NairaAI Solutions',
    tagline: 'Artificial Intelligence for African Businesses',
    description: 'Custom AI chatbots, automation tools, and machine learning solutions built specifically for Nigerian and African businesses.',
    price: '₦45,000/mo', country: 'Nigeria',
    views: 9800, clicks: 1200,
    contact: '+2348099887766', whatsapp: '2348099887766',
    website: 'https://nairaai.com',
    tags: ['AI', 'Automation', 'ML'],
    verified: false, trending: true,
    color: '#8b5cf6',
  },
  {
    id: 7, featured: false,
    logo: '🏠', category: 'Real Estate',
    name: 'Propertyng Hub',
    tagline: 'Find Your Dream Home in Nigeria',
    description: 'Nigeria\'s fastest growing real estate marketplace. Over 50,000 listings across Lagos, Abuja, and Port Harcourt.',
    price: '₦30,000/mo', country: 'Nigeria',
    views: 28400, clicks: 4100,
    contact: '+2348033445566', whatsapp: '2348033445566',
    website: 'https://propertynghub.com',
    tags: ['Real Estate', 'Property', 'Housing'],
    verified: true, trending: false,
    color: '#10b981',
  },
  {
    id: 8, featured: false,
    logo: '💰', category: 'Finance',
    name: 'InvestNaira',
    tagline: 'Smart Investments for Smart Nigerians',
    description: 'Licensed investment platform offering mutual funds, stocks, bonds, and dollar savings. Start with as little as ₦1,000.',
    price: '₦40,000/mo', country: 'Nigeria',
    views: 19700, clicks: 3300,
    contact: '+2347099112233', whatsapp: '2347099112233',
    website: 'https://investnaira.com',
    tags: ['Finance', 'Investment', 'Savings'],
    verified: true, trending: false,
    color: '#f59e0b',
  },
  {
    id: 9, featured: false,
    logo: '🎤', category: 'Events',
    name: 'Lagos Music Fest 2025',
    tagline: 'The Biggest Music Festival in West Africa',
    description: '3 days of non-stop Afrobeats, Afropop, and global music. 50+ artists, 30,000 attendees, unlimited experiences.',
    price: '₦18,000/mo', country: 'Nigeria',
    views: 41000, clicks: 7200,
    contact: '+2348077889900', whatsapp: '2348077889900',
    website: 'https://lagosmusicfest.com',
    tags: ['Events', 'Music', 'Festival'],
    verified: false, trending: true,
    color: '#ff0080',
  },
];

export const PLANS = [
  {
    name: 'Free',
    price: '₦0',
    period: 'forever',
    color: '#6b7280',
    glow: 'rgba(107,114,128,0.3)',
    badge: 'GET STARTED',
    features: [
      '1 business listing',
      'Basic profile page',
      'Limited visibility',
      'Standard search placement',
      'Email support',
    ],
    disabled: ['Analytics dashboard', 'Featured badge', 'Priority ranking', 'Homepage placement'],
  },
  {
    name: 'Starter',
    price: '₦7,500',
    period: '/month',
    color: '#00f0ff',
    glow: 'rgba(0,240,255,0.3)',
    badge: 'MOST POPULAR',
    popular: true,
    features: [
      '3 business listings',
      'Featured badge on listings',
      'Basic analytics dashboard',
      'Better search visibility',
      'WhatsApp contact button',
      'Priority email support',
    ],
    disabled: ['Homepage placement', 'AI insights', 'Global visibility'],
  },
  {
    name: 'Pro',
    price: '₦20,000',
    period: '/month',
    color: '#8b5cf6',
    glow: 'rgba(139,92,246,0.3)',
    badge: 'RECOMMENDED',
    features: [
      '10 business listings',
      'Homepage carousel placement',
      'Priority search ranking',
      'Full analytics + lead tracker',
      'AI campaign assistant',
      'Business verification badge',
      'Custom banner ads',
      '24/7 priority support',
    ],
    disabled: ['Hero banner ads', 'Enterprise dashboard'],
  },
  {
    name: 'Enterprise',
    price: '₦75,000',
    period: '/month',
    color: '#ff0080',
    glow: 'rgba(255,0,128,0.4)',
    badge: '🔥 ELITE',
    features: [
      'Unlimited listings',
      'Hero banner ad placement',
      'Top-of-page premium position',
      'Global visibility boost',
      'Dedicated account manager',
      'Custom AI marketing strategy',
      'Business verification (Gold)',
      'API access + integrations',
      'White-label options',
      'Revenue share program',
    ],
    disabled: [],
  },
];

export const BLOG_POSTS = [
  {
    id: 1, category: 'Marketing Tips',
    title: '10 Proven Strategies to Boost Your Nigerian Business Online',
    excerpt: 'Discover how top Nigerian businesses use digital advertising to triple their customer acquisition rate in just 90 days.',
    date: 'Jan 15, 2025', readTime: '7 min read',
    views: 12400, emoji: '📈',
  },
  {
    id: 2, category: 'AI Trends',
    title: 'How AI is Revolutionizing Advertising in Africa',
    excerpt: 'From automated ad copy to predictive targeting, artificial intelligence is changing the way African businesses reach customers.',
    date: 'Jan 22, 2025', readTime: '5 min read',
    views: 8900, emoji: '🤖',
  },
  {
    id: 3, category: 'Success Stories',
    title: 'From Zero to ₦50M: How LaunchPad Used Rackyweb to Scale',
    excerpt: 'The inspiring story of how a small Lagos startup used targeted digital advertising to grow 10x in 12 months.',
    date: 'Feb 2, 2025', readTime: '9 min read',
    views: 21300, emoji: '🚀',
  },
  {
    id: 4, category: 'Business Growth',
    title: 'The Ultimate Guide to WhatsApp Business Marketing in 2025',
    excerpt: 'WhatsApp has 90M+ users in Nigeria. Learn how to convert them into paying customers with these advanced strategies.',
    date: 'Feb 10, 2025', readTime: '8 min read',
    views: 16700, emoji: '💬',
  },
  {
    id: 5, category: 'Advertising News',
    title: 'Digital Ad Spend in Nigeria to Hit ₦2 Trillion by 2026',
    excerpt: 'New research shows unprecedented growth in Nigerian digital advertising, with mobile video ads leading the surge.',
    date: 'Feb 18, 2025', readTime: '4 min read',
    views: 9200, emoji: '💰',
  },
  {
    id: 6, category: 'SEO',
    title: 'How to Get Your Nigerian Business Found on Google in 2025',
    excerpt: 'Local SEO strategies that actually work for Nigerian businesses. Step-by-step guide to dominating search results.',
    date: 'Mar 1, 2025', readTime: '11 min read',
    views: 31500, emoji: '🔍',
  },
];

export const EARN_FEATURES = [
  {
    icon: '📈',
    title: 'Traffic Growth',
    desc: 'Get your business in front of 950,000+ monthly visitors actively searching for services like yours.',
    stat: '300% avg traffic increase',
    color: '#00f0ff',
  },
  {
    icon: '🎯',
    title: 'Lead Generation',
    desc: 'Our smart targeting system connects you with high-intent buyers ready to make a purchase decision.',
    stat: '5x more qualified leads',
    color: '#8b5cf6',
  },
  {
    icon: '👁️',
    title: 'Brand Visibility',
    desc: 'Premium placements on homepage, search results, and category pages ensure maximum brand exposure.',
    stat: '10M+ monthly impressions',
    color: '#ff0080',
  },
  {
    icon: '👥',
    title: 'Customer Acquisition',
    desc: 'Convert browsers into buyers with compelling ad formats, direct WhatsApp integration, and instant contact.',
    stat: '67% lower cost per acquisition',
    color: '#10b981',
  },
  {
    icon: '📊',
    title: 'Conversion Tracking',
    desc: 'Real-time analytics dashboard tracks every click, lead, and conversion from your ad campaigns.',
    stat: 'Real-time data insights',
    color: '#f59e0b',
  },
  {
    icon: '💰',
    title: 'Revenue Growth',
    desc: 'Businesses on Rackyweb Promote report an average 280% ROI on their advertising investment.',
    stat: '280% average ROI',
    color: '#00f0ff',
  },
];

export const DASHBOARD_CAMPAIGNS = [
  { id: 1, name: 'LaunchPad Summer Campaign', status: 'active', views: 12840, clicks: 1203, leads: 89, budget: 50000, spent: 34200, startDate: '2025-01-01', endDate: '2025-03-31' },
  { id: 2, name: 'Product Launch - NairaAI v2', status: 'paused', views: 5600, clicks: 420, leads: 31, budget: 20000, spent: 12000, startDate: '2025-01-15', endDate: '2025-02-28' },
  { id: 3, name: 'Fashion Week Promo', status: 'completed', views: 28900, clicks: 3100, leads: 245, budget: 30000, spent: 30000, startDate: '2024-12-01', endDate: '2024-12-31' },
];
